# Site settings
title: Julien 
tagline: Software Engineer
title_desc: Hello there~
email: in progress
description: > # this means to ignore newlines until "baseurl:"
  Software Engineer. Tryer of things. Life. Sadly not a lawyer.
  If you reached this site, you found me. I like to dabble in things.
  Learning is my passion. Cute ain't it?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.madeinjulien.com" # the base hostname & protocol for your site
twitter_username: nuliej_1
github_username:  psmagicman

# Build settings
markdown: kramdown
